import React from "react";
import Head from "next/head";
import MetaSeo from "~/components/MetaSeo";

export default function Layout({ children }: { children: React.ReactNode }) {
  const dataSeo = {
    url: "https://nextjs.org",
    type: "website",
    title: "Layout page",
    description: "",
    domain: "",
    card: "summary_large_image",
  };

  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <title>NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MetaSeo props={{...dataSeo}} />
      <div className="min-h-screen bg-black *:text-white">{children}</div>
    </>
  );
}
